// 1. Enum Definitions (Must match your Postgres ENUMs exactly)
export type SpendingLevel = 'Low' | 'Medium' | 'High';
export type LoyaltyTier = 'Tier 1' | 'Tier 2' | 'Tier 3';
export type CustomerStatus = 'Bronze' | 'Silver' | 'Gold' | 'Platinum';
export type Gender = 'Male' | 'Female' | 'Other' | 'Prefer Not to Say';

// 2. The Main Interface
export interface ICustomer {
  // Primary Keys & Identifiers
  id: string; // UUID
  internal_serial: number; // BIGINT (Handled by DB)
  display_id: string; // VARCHAR (Generated by your 'generate_public_customer_id' function)
  company_id: string; // UUID (Foreign Key)

  // Personal Info
  full_name: string;
  phone_number: string | null;
  email: string;
  date_of_birth: string | Date | null; // DATE
  gender: Gender | null;
  preferred_location: string | null;
  favorite_orders: string[] | null; // TEXT[]
  notes: string | null;

  // Financials (Calculated by 'sync_customer_financials' trigger)
  total_spent: number; // DECIMAL(12, 2)
  visits_count: number; // INTEGER
  average_spend: number; // GENERATED ALWAYS AS...

  // Status & Logic
  spending_level: SpendingLevel;
  loyalty_tier: LoyaltyTier;
  customer_status: CustomerStatus;
  feedback_score: number; // DECIMAL(3, 2)

  // Dates
  last_visit: string | Date | null;
  created_at: string | Date; // TIMESTAMP WITH TIME ZONE
}

// 3. Helper Type for Creating a Customer
// Use this when inserting data so you don't accidentally try to provide 
// fields that the Database handles automatically (like display_id or total_spent)
export type CreateCustomerInput = Omit<
  ICustomer, 
  'id' | 'internal_serial' | 'display_id' | 'average_spend' | 'total_spent' | 'visits_count' | 'created_at'
>;


// src/types/database.ts

export interface ITransaction {
  id: string;          // UUID Primary Key
  customer_id: string; // UUID Foreign Key
  company_id: string;  // UUID Foreign Key (used by your triggers)
  amount: number;      // DECIMAL(12, 2)
  created_at: string | Date;
}

/**
 * For adding new transactions, we only need these three fields.
 * Everything else (id, created_at) is handled by the DB.
 */
export type CreateTransactionInput = Omit<ITransaction, 'id' | 'created_at'>;


export interface ICompany {
  id: string;
  name: string;
  slug: string;
  logo_url: string | null;
  is_active: boolean;
  created_at: string;
}

export interface ITenantSettings {
  company_id: string;
  silver_threshold: number;
  gold_threshold: number;
  plat_threshold: number;
  spend_level_med_min: number;
  spend_level_high_min: number;
  tier2_visit_min: number;
  tier3_visit_min: number;
}

export type UserRole = 'admin' | 'staff' | 'customer';

export interface IUser {
  id: string;
  company_id: string;
  full_name: string;
  email: string;
  password?: string; // Optional so we don't send it back to frontend
  role: UserRole;
  created_at: string;
}

//Attendance
export interface AttendanceLog {
  id: string;
  employee_id: string;
  clock_in: string | null;
  clock_out: string | null;
  break_start: string | null;
  break_end: string | null;
  log_status: string;
  log_date: string;
}

export interface AttendanceResponse {
  summary: number[]; // [WorkedHours, OvertimeHours, Leaves, Absents]
  calendar: { date: string; status: string }[];
  shifts: { 
    id: string; 
    date: string; 
    clockIn: string; 
    clockOut: string; 
    durationHours: number;
  }[];
}
